name: Setup Script Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DL_PATH: "$HOME/Downloads"
  HACKGEN_VERSION: "2.9.0"

jobs:
  test-ubuntu:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache HackGenNerd Font
        id: cache-hackgen-nf
        uses: actions/cache@v4
        with:
          path: ${{ env.DL_PATH }}/HackGen_NF_v${{ env.HACKGEN_VERSION }}.zip
          key: ${{ runner.os }}-hackgen-nf-${{ env.HACKGEN_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hackgen-nf-${{ env.HACKGEN_VERSION }}

      - name: Download HackGenNerd Font
        if: steps.cache-hackgen-nf.outputs.cache-hit != 'true'
        run: |
          wget -P "${{ env.DL_PATH }}" "https://github.com/yuru7/HackGen/releases/download/v${{ env.HACKGEN_VERSION }}/HackGen_NF_v${{ env.HACKGEN_VERSION }}.zip"

      - name: Cache HackGen
        id: cache-hackgen
        uses: actions/cache@v4
        with:
          path: ${{ env.DL_PATH }}/HackGen_v${{ env.HACKGEN_VERSION }}.zip
          key: ${{ runner.os }}-hackgen-${{ env.HACKGEN_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hackgen-${{ env.HACKGEN_VERSION }}

      - name: Download HackGen
        if: steps.cache-hackgen.outputs.cache-hit != 'true'
        run: |
          wget -P "${{ env.DL_PATH }}" "https://github.com/yuru7/HackGen/releases/download/v${{ env.HACKGEN_VERSION }}/HackGen_v${{ env.HACKGEN_VERSION }}.zip"

      - name: Cache Hyper.js
        id: cache-hyper
        uses: actions/cache@v4
        with:
          path: ${{ env.DL_PATH }}/deb
          key: ${{ runner.os }}-hyper-js
          restore-keys: |
            ${{ runner.os }}-hyper-js

      - name: Download Hyper.js
        if: steps.cache-hyper.outputs.cache-hit != 'true'
        run: |
          wget -P "${{ env.DL_PATH }}" "https://releases.hyper.is/download/deb"

      - uses: ./.github/actions/setup-script

  test-macos:
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache HackGenNerd Font
        id: cache-hackgen-nf
        uses: actions/cache@v4
        with:
          path: ${{ env.DL_PATH }}/HackGen_NF_v${{ env.HACKGEN_VERSION }}.zip
          key: ${{ runner.os }}-hackgen-nf-${{ env.HACKGEN_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hackgen-nf-${{ env.HACKGEN_VERSION }}

      - name: Download HackGenNerd Font
        if: steps.cache-hackgen-nf.outputs.cache-hit != 'true'
        run: |
          wget -P "${{ env.DL_PATH }}" "https://github.com/yuru7/HackGen/releases/download/v${{ env.HACKGEN_VERSION }}/HackGen_NF_v${{ env.HACKGEN_VERSION }}.zip"

      - name: Cache HackGen
        id: cache-hackgen
        uses: actions/cache@v4
        with:
          path: ${{ env.DL_PATH }}/HackGen_v${{ env.HACKGEN_VERSION }}.zip
          key: ${{ runner.os }}-hackgen-${{ env.HACKGEN_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hackgen-${{ env.HACKGEN_VERSION }}

      - name: Download HackGen
        if: steps.cache-hackgen.outputs.cache-hit != 'true'
        run: |
          wget -P "${{ env.DL_PATH }}" "https://github.com/yuru7/HackGen/releases/download/v${{ env.HACKGEN_VERSION }}/HackGen_v${{ env.HACKGEN_VERSION }}.zip"

      - name: Cache Hyper.js
        id: cache-hyper
        uses: actions/cache@v4
        with:
          path: ${{ env.DL_PATH }}/hyper_${{ env.HYPER_VERSION }}_amd64.deb
          key: ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hyper-${{ env.HYPER_VERSION }}

      - name: Download Hyper.js
        if: steps.cache-hyper.outputs.cache-hit != 'true'
        run: |
          wget -P "${{ env.DL_PATH }}" "https://releases.hyper.is/download/deb"

      - name: Enable Gatekeeper
        run: sudo spctl --master-enable

      - uses: ./.github/actions/setup-script
