name: Setup Script Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  HACKGEN_VERSION: "2.9.0"
  DL_PATH: "$HOME/Downloads"

jobs:
  test-ubuntu:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache HackGenNerd Font
        id: cache-hackgen-nf
        uses: actions/cache@v4
        with:
          path: ${{ env.DL_PATH }}/HackGen_NF_v${{ env.HACKGEN_VERSION }}.zip
          key: ${{ runner.os }}-hackgen-nf-${{ env.HACKGEN_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hackgen-nf-${{ env.HACKGEN_VERSION }}
      - name: Download HackGenNerd Font
        if: steps.cache-hackgen-nf.outputs.cache-hit != 'true'
        run: |
          wget -P "${{ env.DL_PATH }}" "https://github.com/yuru7/HackGen/releases/download/v${{ env.HACKGEN_VERSION }}/HackGen_NF_v${{ env.HACKGEN_VERSION }}.zip"
      - uses: ./.github/actions/setup-script

  test-macos:
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-script
      - name: Enable Gatekeeper
        run: sudo spctl --master-enable
