name: Setup Script Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-ubuntu:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 実行権限を設定
      run: chmod +x setup.sh
    - name: セットアップスクリプトを実行
      run: |
        ./setup.sh

  test-macos:
    timeout-minutes: 10
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: 実行権限を設定
      run: chmod +x setup.sh
    - name: セットアップスクリプトを実行
      run: |
        ./setup.sh
